services:
  - type: web
    name: todoist-voice-plugin
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: LOCAL_TESTING
        value: "false"
      - key: TODOIST_API_KEY
        value: "d5ac866e69ae82890339f307ee69c6814e3ab0a1"
    autoDeploy: true 